spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tonzinhos_db
    username: root
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: chave-secreta-mudar-em-producao
  expiration: 86400000

server:
  port: 8080